### ISSUE TITLE
Running rake fails

### ISSUE THREAD

**Issue by sattelbergerp** [learn-co-curriculum/rails-pollywog-ranch#24] opened 2017-06-07 23:27 UTC
Running rake fails with the following error:    
```
bundle exec rake
/usr/local/bin/rake:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/specifications/bin/rake (LoadError)
	from /usr/local/bin/rake:23:in `<main>'
```
I fixed this on a different lab by running 'bundle update rake' and 'bundle update rspec-rails' (rspec-rails must also be updated as a rake update breaks the default version) however on this lab I get the following error:
```
bundle update rspec-rails
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies........................................
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 4.2.0)

  In Gemfile:
    activemodel (= 3.1.12)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
Running 'bundle update' changes nothing.
OS: Ubuntu 16.04
Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

Edit: I am not using the IDE.

**Comment by gj** [comment] 2017-06-27 15:35
Hi @sattelbergerp !

I'm unable to reproduce the issue — perhaps it's a problem with your local environment?

The `Gemfile` and `Gemfile.lock` look okay to me.

**Comment by gj** [comment] 2017-07-06 22:01
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 🙂

**Closed by gj** 2017-07-06 22:01 UTC
Labels: Product
